login: "ikornienko@spscommerce.com"
password: "Fynfyfyfh555555!"
emailFolder: "Inbox/Vadim Bagatskiy"
imapHost: "outlook.office365.com"
toRecipient: "ikornienko@spscommerce.com"
ccRecipient: "ikornienko@spscommerce.com"
emailFault: 810
minMessageCount: 5
properties:
  mail.imap.port: "993"
  mail.smtp.starttls.enable: "true"
  mail.smtp.host: "smtp.office365.com"
  mail.smtp.port: "587"
  mail.smtp.auth: "true"
errorFolderEDI1: "D:/work/DirectEDI/09152017/EDI1"
prodFolderEDI1: "D:/work/DirectEDI/09152017/updated"
archiveFolderEDI1: "D:/work/DirectEDI/09152017/archive"
errorFolderEDI2: "D:/work/DirectEDI/09152017/EDI2"
prodFolderEDI2: "D:/work/DirectEDI/09152017/updated"
archiveFolderEDI2: "D:/work/DirectEDI/09152017/archive"